"toml++" = { git = "https://github.com/marzer/tomlplusplus.git", aliases = ["tomlplusplus"], header = true }
spdlog = { git = "https://github.com/gabime/spdlog.git", header = true }
CLI11 = { git = "https://github.com/CLIUtils/CLI11.git", aliases = ["CLI"], header = true }
